version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: react-native-reanimated
    versions:
    - 2.1.0
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: react-native-web
    versions:
    - 0.14.13
    - 0.15.0
    - 0.15.1
    - 0.15.3
    - 0.15.5
    - 0.15.6
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.51
    - 0.63.52
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: metro-config
    versions:
    - 0.65.2
  - dependency-name: expo
    versions:
    - 40.0.1
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
  - dependency-name: axios
    versions:
    - 0.21.1
